//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails15과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllStoresTotalAmount01 {
            get {
                return ResourceManager.GetString("AllStoresTotalAmount01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails16과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllStoresTotalAmount02 {
            get {
                return ResourceManager.GetString("AllStoresTotalAmount02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails05과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BuyDate {
            get {
                return ResourceManager.GetString("BuyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMM {
            get {
                return ResourceManager.GetString("COMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringEndMark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EndMark {
            get {
                return ResourceManager.GetString("EndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXCOMM {
            get {
                return ResourceManager.GetString("EXCOMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails06과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodsAmt {
            get {
                return ResourceManager.GetString("GoodsAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodsDetailsTitle {
            get {
                return ResourceManager.GetString("GoodsDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails04과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodsName {
            get {
                return ResourceManager.GetString("GoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails05과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodsPrice {
            get {
                return ResourceManager.GetString("GoodsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails08과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LandingDate {
            get {
                return ResourceManager.GetString("LandingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails07과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LandingPlace {
            get {
                return ResourceManager.GetString("LandingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringLine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails04과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string National {
            get {
                return ResourceManager.GetString("National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringOperationName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Operation_corprate_name {
            get {
                return ResourceManager.GetString("Operation_corprate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PassPortNo {
            get {
                return ResourceManager.GetString("PassPortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PassPortType {
            get {
                return ResourceManager.GetString("PassPortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails10과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RefundAmt {
            get {
                return ResourceManager.GetString("RefundAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRefundWayDesc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RefundWayDesc {
            get {
                return ResourceManager.GetString("RefundWayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRefundWayName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RefundWayName {
            get {
                return ResourceManager.GetString("RefundWayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRefundWayQQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RefundWayQQ {
            get {
                return ResourceManager.GetString("RefundWayQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRefundWayUPI과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RefundWayUPI {
            get {
                return ResourceManager.GetString("RefundWayUPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRePublish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RePublish {
            get {
                return ResourceManager.GetString("RePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails06과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Residence {
            get {
                return ResourceManager.GetString("Residence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRetailer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RetailerTitle {
            get {
                return ResourceManager.GetString("RetailerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails07과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaleAmt {
            get {
                return ResourceManager.GetString("SaleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRetailer03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRetailer04과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SellerAddr {
            get {
                return ResourceManager.GetString("SellerAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType02Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipNo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipNo {
            get {
                return ResourceManager.GetString("SlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType01 {
            get {
                return ResourceManager.GetString("SlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType01AddText01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType01AddText01 {
            get {
                return ResourceManager.GetString("SlipType01AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType01Desc01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType01Desc01 {
            get {
                return ResourceManager.GetString("SlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType01Desc02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType01Desc02 {
            get {
                return ResourceManager.GetString("SlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType01Desc03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType01Desc03 {
            get {
                return ResourceManager.GetString("SlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType01Desc04과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType01Desc04 {
            get {
                return ResourceManager.GetString("SlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType02 {
            get {
                return ResourceManager.GetString("SlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType02AddText01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType02AddText01 {
            get {
                return ResourceManager.GetString("SlipType02AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType02Desc01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType02Desc01 {
            get {
                return ResourceManager.GetString("SlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType02Desc02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType02Desc02 {
            get {
                return ResourceManager.GetString("SlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType03 {
            get {
                return ResourceManager.GetString("SlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType04과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType04 {
            get {
                return ResourceManager.GetString("SlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType05과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType05 {
            get {
                return ResourceManager.GetString("SlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType06과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType06 {
            get {
                return ResourceManager.GetString("SlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringSlipType06No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SlipType06No {
            get {
                return ResourceManager.GetString("SlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails08과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaxAmt {
            get {
                return ResourceManager.GetString("TaxAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRetailer01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaxOffice {
            get {
                return ResourceManager.GetString("TaxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringRetailer02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaxPlace {
            get {
                return ResourceManager.GetString("TaxPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails09과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalAmt {
            get {
                return ResourceManager.GetString("TotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails13과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalFeeAmt {
            get {
                return ResourceManager.GetString("TotalFeeAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails12과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalRefundAmt {
            get {
                return ResourceManager.GetString("TotalRefundAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails11과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalSaleAmt {
            get {
                return ResourceManager.GetString("TotalSaleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringGoodsDetails14과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalTaxAmt {
            get {
                return ResourceManager.GetString("TotalTaxAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringTouristDetails과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TouristDetailsTitle {
            get {
                return ResourceManager.GetString("TouristDetailsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   StringGoodsDetails18(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodsDivision
        {
            get
            {
                return ResourceManager.GetString("GoodsDivision", resourceCulture);
            }
        }

        /// <summary>
        ///   StringGoodsDetails17(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodsSubcategory
        {
            get
            {
                return ResourceManager.GetString("GoodsSubcategory", resourceCulture);
            }
        }

    }
}
