//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourcesko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcesko_KR() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.Resourcesko-KR", typeof(Resourcesko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -- END --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringEndMark {
            get {
                return ResourceManager.GetString("StringEndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOODS DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails {
            get {
                return ResourceManager.GetString("StringGoodsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구입년월일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails01 {
            get {
                return ResourceManager.GetString("StringGoodsDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소모품과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails02 {
            get {
                return ResourceManager.GetString("StringGoodsDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일반품목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails03 {
            get {
                return ResourceManager.GetString("StringGoodsDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails04 {
            get {
                return ResourceManager.GetString("StringGoodsDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails05 {
            get {
                return ResourceManager.GetString("StringGoodsDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails06 {
            get {
                return ResourceManager.GetString("StringGoodsDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   판매가격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails07 {
            get {
                return ResourceManager.GetString("StringGoodsDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   면세금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails08 {
            get {
                return ResourceManager.GetString("StringGoodsDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합계금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails09 {
            get {
                return ResourceManager.GetString("StringGoodsDetails09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반환금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails10 {
            get {
                return ResourceManager.GetString("StringGoodsDetails10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총합계금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails11 {
            get {
                return ResourceManager.GetString("StringGoodsDetails11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총반환액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails12 {
            get {
                return ResourceManager.GetString("StringGoodsDetails12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총수수료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails13 {
            get {
                return ResourceManager.GetString("StringGoodsDetails13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총면세금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails14 {
            get {
                return ResourceManager.GetString("StringGoodsDetails14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전 점포 소모품 판매액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails15 {
            get {
                return ResourceManager.GetString("StringGoodsDetails15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전 점포 일반물품 판매액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails16 {
            get {
                return ResourceManager.GetString("StringGoodsDetails16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---------------------------------------------------------------과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringLine {
            get {
                return ResourceManager.GetString("StringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運営会社과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringOperationName {
            get {
                return ResourceManager.GetString("StringOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재발행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRePublish {
            get {
                return ResourceManager.GetString("StringRePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETAILER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer {
            get {
                return ResourceManager.GetString("StringRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소속세무서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer01 {
            get {
                return ResourceManager.GetString("StringRetailer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   납세지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer02 {
            get {
                return ResourceManager.GetString("StringRetailer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   판매지성명혹은상호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer03 {
            get {
                return ResourceManager.GetString("StringRetailer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   판매장주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer04 {
            get {
                return ResourceManager.GetString("StringRetailer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전표번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipNo {
            get {
                return ResourceManager.GetString("StringSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수출면세물품구입기록표과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01 {
            get {
                return ResourceManager.GetString("StringSlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ① 일본에서 출국할 때 또는 거주자가 될 때 그 출항지를 관할하는 세관장 또는 그 주소 혹은 거소 소재지를 관할하는 세무서장에게 구입기록표를 제출해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ② 일본에서 출국할 때까지는 구입기록표를 여권 등에서 떼어내면안됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ③ 면세로 구입한 물품을 일본 출국시 소지하지 않은 경우에는 그 구입한 물품에 대해 면제된 소비세액(지방 소비세를 포함)에 상당하는 액수가 징수됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc03 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ④ ③의 경우에서 재해 및 기타 부득이한 사정으로 인해 면세로 구입한 물품을 분실한 관계로 반출하지 않는 것에 대해 세관장의 승인을 받았을 때, 또는 이미 반출했음을 증명하는 서류를 출항지를 관할하는 세관장에게 제출했을 때는 소비세(지방 소비세를 포함)에 상당하는 액수가 징수되지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc04 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///면세물품구입자확약서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02 {
            get {
                return ResourceManager.GetString("StringSlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 소모품을 구입한 날로부터 30일 이내에 수출하는 것으로 구입해 일본에서 처분하지 않는 것을 서약합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 일반 물품을 일본에서 최종적으로는 수출하는 것으로 구입해 일본에서 처분하지 않기로 서약합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名　Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Signature {
            get {
                return ResourceManager.GetString("StringSlipType02Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///수출면세물품구입기록표(보관용)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType03 {
            get {
                return ResourceManager.GetString("StringSlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구입자보관용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType04 {
            get {
                return ResourceManager.GetString("StringSlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수출물품판매자보관용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType05 {
            get {
                return ResourceManager.GetString("StringSlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합산발행전표과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06 {
            get {
                return ResourceManager.GetString("StringSlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합산발행순번과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06No {
            get {
                return ResourceManager.GetString("StringSlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOURIST&apos;S DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails {
            get {
                return ResourceManager.GetString("StringTouristDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여권 등 종류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails01 {
            get {
                return ResourceManager.GetString("StringTouristDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여권번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails02 {
            get {
                return ResourceManager.GetString("StringTouristDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구매자성명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails03 {
            get {
                return ResourceManager.GetString("StringTouristDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   국적과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails04 {
            get {
                return ResourceManager.GetString("StringTouristDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생년월일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails05 {
            get {
                return ResourceManager.GetString("StringTouristDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   체류자격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails06 {
            get {
                return ResourceManager.GetString("StringTouristDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상륙지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails07 {
            get {
                return ResourceManager.GetString("StringTouristDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상륙년월일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails08 {
            get {
                return ResourceManager.GetString("StringTouristDetails08", resourceCulture);
            }
        }


        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails17
        {
            get
            {
                return ResourceManager.GetString("StringGoodsDetails17", resourceCulture);
            }
        }

        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails18
        {
            get
            {
                return ResourceManager.GetString("StringGoodsDetails18", resourceCulture);
            }
        }
    }
}
