//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gtf_logo {
            get {
                object obj = ResourceManager.GetObject("gtf_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jpn_logo {
            get {
                object obj = ResourceManager.GetObject("jpn_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- END --.
        /// </summary>
        internal static string StringEndMark {
            get {
                return ResourceManager.GetString("StringEndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効でない日付形式です。.
        /// </summary>
        internal static string StringErrLandingDate {
            get {
                return ResourceManager.GetString("StringErrLandingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOODS DETAILS.
        /// </summary>
        internal static string StringGoodsDetails {
            get {
                return ResourceManager.GetString("StringGoodsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入年月日.
        /// </summary>
        internal static string StringGoodsDetails01 {
            get {
                return ResourceManager.GetString("StringGoodsDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消耗品.
        /// </summary>
        internal static string StringGoodsDetails02 {
            get {
                return ResourceManager.GetString("StringGoodsDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般物品.
        /// </summary>
        internal static string StringGoodsDetails03 {
            get {
                return ResourceManager.GetString("StringGoodsDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        internal static string StringGoodsDetails04 {
            get {
                return ResourceManager.GetString("StringGoodsDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価.
        /// </summary>
        internal static string StringGoodsDetails05 {
            get {
                return ResourceManager.GetString("StringGoodsDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        internal static string StringGoodsDetails06 {
            get {
                return ResourceManager.GetString("StringGoodsDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売価格.
        /// </summary>
        internal static string StringGoodsDetails07 {
            get {
                return ResourceManager.GetString("StringGoodsDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 免税額.
        /// </summary>
        internal static string StringGoodsDetails08 {
            get {
                return ResourceManager.GetString("StringGoodsDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計価額.
        /// </summary>
        internal static string StringGoodsDetails09 {
            get {
                return ResourceManager.GetString("StringGoodsDetails09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返金額.
        /// </summary>
        internal static string StringGoodsDetails10 {
            get {
                return ResourceManager.GetString("StringGoodsDetails10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総合計価額.
        /// </summary>
        internal static string StringGoodsDetails11 {
            get {
                return ResourceManager.GetString("StringGoodsDetails11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総返金額.
        /// </summary>
        internal static string StringGoodsDetails12 {
            get {
                return ResourceManager.GetString("StringGoodsDetails12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総手数料.
        /// </summary>
        internal static string StringGoodsDetails13 {
            get {
                return ResourceManager.GetString("StringGoodsDetails13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総免税額.
        /// </summary>
        internal static string StringGoodsDetails14 {
            get {
                return ResourceManager.GetString("StringGoodsDetails14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全店合計消耗品販売額.
        /// </summary>
        internal static string StringGoodsDetails15 {
            get {
                return ResourceManager.GetString("StringGoodsDetails15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全店合計一般物品販売額.
        /// </summary>
        internal static string StringGoodsDetails16 {
            get {
                return ResourceManager.GetString("StringGoodsDetails16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品目大分類.
        /// </summary>
        internal static string StringGoodsDetails17 {
            get {
                return ResourceManager.GetString("StringGoodsDetails17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品目中分類.
        /// </summary>
        internal static string StringGoodsDetails18 {
            get {
                return ResourceManager.GetString("StringGoodsDetails18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------------------.
        /// </summary>
        internal static string StringLine {
            get {
                return ResourceManager.GetString("StringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運営会社.
        /// </summary>
        internal static string StringOperationName {
            get {
                return ResourceManager.GetString("StringOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旅券.
        /// </summary>
        internal static string StringPassPortEtc01 {
            get {
                return ResourceManager.GetString("StringPassPortEtc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外交官.
        /// </summary>
        internal static string StringPassPortEtc02 {
            get {
                return ResourceManager.GetString("StringPassPortEtc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗組員上陸許可書.
        /// </summary>
        internal static string StringPassPortEtc03 {
            get {
                return ResourceManager.GetString("StringPassPortEtc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緊急上陸許可書.
        /// </summary>
        internal static string StringPassPortEtc04 {
            get {
                return ResourceManager.GetString("StringPassPortEtc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遭難上陸許可書.
        /// </summary>
        internal static string StringPassPortEtc05 {
            get {
                return ResourceManager.GetString("StringPassPortEtc05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIPT.
        /// </summary>
        internal static string StringReceip {
            get {
                return ResourceManager.GetString("StringReceip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レシート貼付.
        /// </summary>
        internal static string StringReceiptAdd {
            get {
                return ResourceManager.GetString("StringReceiptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID.
        /// </summary>
        internal static string StringRefundSerial {
            get {
                return ResourceManager.GetString("StringRefundSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUND DETAIL.
        /// </summary>
        internal static string StringRefundway {
            get {
                return ResourceManager.GetString("StringRefundway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 還付方法.
        /// </summary>
        internal static string StringRefundWayDesc {
            get {
                return ResourceManager.GetString("StringRefundWayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 還付方法.
        /// </summary>
        internal static string StringRefundWayName {
            get {
                return ResourceManager.GetString("StringRefundWayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / QQID .
        /// </summary>
        internal static string StringRefundWayQQ {
            get {
                return ResourceManager.GetString("StringRefundWayQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / UPI No. .
        /// </summary>
        internal static string StringRefundWayUPI {
            get {
                return ResourceManager.GetString("StringRefundWayUPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再発行.
        /// </summary>
        internal static string StringRePublish {
            get {
                return ResourceManager.GetString("StringRePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETAILER.
        /// </summary>
        internal static string StringRetailer {
            get {
                return ResourceManager.GetString("StringRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所轄税務署.
        /// </summary>
        internal static string StringRetailer01 {
            get {
                return ResourceManager.GetString("StringRetailer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納税地.
        /// </summary>
        internal static string StringRetailer02 {
            get {
                return ResourceManager.GetString("StringRetailer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売者氏名・名称.
        /// </summary>
        internal static string StringRetailer03 {
            get {
                return ResourceManager.GetString("StringRetailer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売場所在地.
        /// </summary>
        internal static string StringRetailer04 {
            get {
                return ResourceManager.GetString("StringRetailer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伝票番号.
        /// </summary>
        internal static string StringSlipNo {
            get {
                return ResourceManager.GetString("StringSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸出免税物品購入記録票.
        /// </summary>
        internal static string StringSlipType01 {
            get {
                return ResourceManager.GetString("StringSlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスポート添付用.
        /// </summary>
        internal static string StringSlipType01AddText01 {
            get {
                return ResourceManager.GetString("StringSlipType01AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ① 本邦から出国する際又は居住者となる際に、その出港地を所轄する税関長又はその住所若しくは居所の所在地を所轄する税務署長に購入記録票を提出しなければなりません。.
        /// </summary>
        internal static string StringSlipType01Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ② 本邦から出国するまでは購入記録票を旅券等から切り離してはいけません。.
        /// </summary>
        internal static string StringSlipType01Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ③ 免税で購入した物品を本邦からの出国の際に所持していなかった場合には、その購入した物品について免除された消費税額（地方消費税を含む。）に相当する額を徴収されます。.
        /// </summary>
        internal static string StringSlipType01Desc03 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ④ ③の場合において、災害その他やむを得ない事情により免税で購入した物品を亡失したため輸出しないことにつき税関長の承認を受けたとき、又は既に輸出したことを証する書類を出港地を所轄する税関長に提出したときは、消費税額（地方消費税を含む。）に相当する額を徴収されません。.
        /// </summary>
        internal static string StringSlipType01Desc04 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最終的に輸出となる物品の
        ///消費税免税購入についての購入者誓約書.
        /// </summary>
        internal static string StringSlipType02 {
            get {
                return ResourceManager.GetString("StringSlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店舗控用.
        /// </summary>
        internal static string StringSlipType02AddText01 {
            get {
                return ResourceManager.GetString("StringSlipType02AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当該消耗品を、購入した日から３０日以内に輸出されるものとして購入し、日本で処分しないことを誓約します。.
        /// </summary>
        internal static string StringSlipType02Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当該一般物品を、日本から最終的には輸出されるものとして購入し、日本で処分しないことを誓約します。.
        /// </summary>
        internal static string StringSlipType02Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 署名　Signature.
        /// </summary>
        internal static string StringSlipType02Signature {
            get {
                return ResourceManager.GetString("StringSlipType02Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸出免税物品購入記録票(控え).
        /// </summary>
        internal static string StringSlipType03 {
            get {
                return ResourceManager.GetString("StringSlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入者控え.
        /// </summary>
        internal static string StringSlipType04 {
            get {
                return ResourceManager.GetString("StringSlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸出免税物品販売者控え.
        /// </summary>
        internal static string StringSlipType05 {
            get {
                return ResourceManager.GetString("StringSlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合算発行伝票.
        /// </summary>
        internal static string StringSlipType06 {
            get {
                return ResourceManager.GetString("StringSlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合算伝票番号.
        /// </summary>
        internal static string StringSlipType06No {
            get {
                return ResourceManager.GetString("StringSlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOURIST&apos;S DETAILS.
        /// </summary>
        internal static string StringTouristDetails {
            get {
                return ResourceManager.GetString("StringTouristDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旅券等の種類.
        /// </summary>
        internal static string StringTouristDetails01 {
            get {
                return ResourceManager.GetString("StringTouristDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号.
        /// </summary>
        internal static string StringTouristDetails02 {
            get {
                return ResourceManager.GetString("StringTouristDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入者氏名.
        /// </summary>
        internal static string StringTouristDetails03 {
            get {
                return ResourceManager.GetString("StringTouristDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国籍.
        /// </summary>
        internal static string StringTouristDetails04 {
            get {
                return ResourceManager.GetString("StringTouristDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生年月日.
        /// </summary>
        internal static string StringTouristDetails05 {
            get {
                return ResourceManager.GetString("StringTouristDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在留資格.
        /// </summary>
        internal static string StringTouristDetails06 {
            get {
                return ResourceManager.GetString("StringTouristDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上陸地.
        /// </summary>
        internal static string StringTouristDetails07 {
            get {
                return ResourceManager.GetString("StringTouristDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上陸年月日.
        /// </summary>
        internal static string StringTouristDetails08 {
            get {
                return ResourceManager.GetString("StringTouristDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton_Close_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton_Close.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton_Print_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton_Print.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
