//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourceszh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourceszh_CN() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.Resourceszh-CN", typeof(Resourceszh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -- END --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringEndMark {
            get {
                return ResourceManager.GetString("StringEndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOODS DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails {
            get {
                return ResourceManager.GetString("StringGoodsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails01 {
            get {
                return ResourceManager.GetString("StringGoodsDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消耗品과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails02 {
            get {
                return ResourceManager.GetString("StringGoodsDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般物品과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails03 {
            get {
                return ResourceManager.GetString("StringGoodsDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails04 {
            get {
                return ResourceManager.GetString("StringGoodsDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   单价과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails05 {
            get {
                return ResourceManager.GetString("StringGoodsDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails06 {
            get {
                return ResourceManager.GetString("StringGoodsDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   销售金额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails07 {
            get {
                return ResourceManager.GetString("StringGoodsDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   免税金额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails08 {
            get {
                return ResourceManager.GetString("StringGoodsDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   销售总额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails09 {
            get {
                return ResourceManager.GetString("StringGoodsDetails09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退税金额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails10 {
            get {
                return ResourceManager.GetString("StringGoodsDetails10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   销售总额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails11 {
            get {
                return ResourceManager.GetString("StringGoodsDetails11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退税总额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails12 {
            get {
                return ResourceManager.GetString("StringGoodsDetails12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手续费总额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails13 {
            get {
                return ResourceManager.GetString("StringGoodsDetails13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   免税总额과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails14 {
            get {
                return ResourceManager.GetString("StringGoodsDetails14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전 점포 소모품 판매액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails15 {
            get {
                return ResourceManager.GetString("StringGoodsDetails15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전 점포 일반물품 판매액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails16 {
            get {
                return ResourceManager.GetString("StringGoodsDetails16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---------------------------------------------------------------과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringLine {
            get {
                return ResourceManager.GetString("StringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運営会社과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringOperationName {
            get {
                return ResourceManager.GetString("StringOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   补发单据과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRePublish {
            get {
                return ResourceManager.GetString("StringRePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETAILER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer {
            get {
                return ResourceManager.GetString("StringRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在税务局과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer01 {
            get {
                return ResourceManager.GetString("StringRetailer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   纳税地点과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer02 {
            get {
                return ResourceManager.GetString("StringRetailer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   销售处或商号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer03 {
            get {
                return ResourceManager.GetString("StringRetailer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   销售处地址과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer04 {
            get {
                return ResourceManager.GetString("StringRetailer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文件号码과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipNo {
            get {
                return ResourceManager.GetString("StringSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出口免税物品购买记录单과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01 {
            get {
                return ResourceManager.GetString("StringSlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ① 从日本出境时或者成为居住者时，需要给管辖其出境港的税官长或者管辖其住所或居住所在地的税务署长提交购买记录表。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ② 从日本出境为止，购买记录表不能从护照等上面摘下来。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ③ 从日本出境时，如果没有携带以免税价购买的物品，将收取购买时所免除的消费税额（包含地方消费税）과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc03 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ④ 如同③的情况，因灾害及其他不得已的情况导致免税价购买的物品丢失而无法搬出的情况时，得到税官长的许可或者向税官长出示已确认搬出的相关证明资料的话，不会收取购买时所免除的消费税额（包含地方消费税）。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc04 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///免税物品購入者誓約書과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02 {
            get {
                return ResourceManager.GetString("StringSlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   从购买日起30天内搬出为前提购买的消耗品，誓约日方将不给予处分。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   购买的一般商品最终从日本搬出，誓约日方不会给予处分。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名　Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Signature {
            get {
                return ResourceManager.GetString("StringSlipType02Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出口免税物品购买记录单(保管用)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType03 {
            get {
                return ResourceManager.GetString("StringSlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   顾客保管用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType04 {
            get {
                return ResourceManager.GetString("StringSlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   销售处保管用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType05 {
            get {
                return ResourceManager.GetString("StringSlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합산발행전표과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06 {
            get {
                return ResourceManager.GetString("StringSlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합산발행순번과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06No {
            get {
                return ResourceManager.GetString("StringSlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOURIST&apos;S DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails {
            get {
                return ResourceManager.GetString("StringTouristDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   护照种类과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails01 {
            get {
                return ResourceManager.GetString("StringTouristDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   护照号码과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails02 {
            get {
                return ResourceManager.GetString("StringTouristDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   购买者姓名과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails03 {
            get {
                return ResourceManager.GetString("StringTouristDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国籍과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails04 {
            get {
                return ResourceManager.GetString("StringTouristDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出生日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails05 {
            get {
                return ResourceManager.GetString("StringTouristDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   滞留资格과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails06 {
            get {
                return ResourceManager.GetString("StringTouristDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   着陆과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails07 {
            get {
                return ResourceManager.GetString("StringTouristDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上陆日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails08 {
            get {
                return ResourceManager.GetString("StringTouristDetails08", resourceCulture);
            }
        }

        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails17
        {
            get
            {
                return ResourceManager.GetString("StringGoodsDetails17", resourceCulture);
            }
        }

        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails18
        {
            get
            {
                return ResourceManager.GetString("StringGoodsDetails18", resourceCulture);
            }
        }
    }
}
