//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceResidence {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceResidence() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.ResourceResidence", typeof(ResourceResidence).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   短期滞在과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence01 {
            get {
                return ResourceManager.GetString("StringResidence01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   公用과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence02 {
            get {
                return ResourceManager.GetString("StringResidence02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   教授과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence03 {
            get {
                return ResourceManager.GetString("StringResidence03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   芸術과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence04 {
            get {
                return ResourceManager.GetString("StringResidence04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   宗教과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence05 {
            get {
                return ResourceManager.GetString("StringResidence05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   報道과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence06 {
            get {
                return ResourceManager.GetString("StringResidence06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投資・経営과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence07 {
            get {
                return ResourceManager.GetString("StringResidence07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   法律・会計業務과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence08 {
            get {
                return ResourceManager.GetString("StringResidence08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   医療과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence09 {
            get {
                return ResourceManager.GetString("StringResidence09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   研究과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence10 {
            get {
                return ResourceManager.GetString("StringResidence10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   教育과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence11 {
            get {
                return ResourceManager.GetString("StringResidence11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   技術과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence12 {
            get {
                return ResourceManager.GetString("StringResidence12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人文知識・国際業務과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence13 {
            get {
                return ResourceManager.GetString("StringResidence13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   企業内転勤과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence14 {
            get {
                return ResourceManager.GetString("StringResidence14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   興行과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence15 {
            get {
                return ResourceManager.GetString("StringResidence15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   技能과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence16 {
            get {
                return ResourceManager.GetString("StringResidence16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   技能実習과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence17 {
            get {
                return ResourceManager.GetString("StringResidence17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文化活動과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence18 {
            get {
                return ResourceManager.GetString("StringResidence18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外交과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence19 {
            get {
                return ResourceManager.GetString("StringResidence19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   留学과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence20 {
            get {
                return ResourceManager.GetString("StringResidence20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   研修과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence21 {
            get {
                return ResourceManager.GetString("StringResidence21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   家族滞在과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence22 {
            get {
                return ResourceManager.GetString("StringResidence22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特定活動과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence23 {
            get {
                return ResourceManager.GetString("StringResidence23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   永住者과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence24 {
            get {
                return ResourceManager.GetString("StringResidence24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本人の配偶者等과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence25 {
            get {
                return ResourceManager.GetString("StringResidence25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   永住者の配偶者等과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence26 {
            get {
                return ResourceManager.GetString("StringResidence26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定住者과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringResidence27 {
            get {
                return ResourceManager.GetString("StringResidence27", resourceCulture);
            }
        }
    }
}
