//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourcesen_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcesen_US() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_Printer.Properties.Resourcesen-US", typeof(Resourcesen_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -- END --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringEndMark {
            get {
                return ResourceManager.GetString("StringEndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOODS DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails {
            get {
                return ResourceManager.GetString("StringGoodsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date of Purchase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails01 {
            get {
                return ResourceManager.GetString("StringGoodsDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commodities과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails02 {
            get {
                return ResourceManager.GetString("StringGoodsDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commodities except consumables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails03 {
            get {
                return ResourceManager.GetString("StringGoodsDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of Commodity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails04 {
            get {
                return ResourceManager.GetString("StringGoodsDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails05 {
            get {
                return ResourceManager.GetString("StringGoodsDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q-ty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails06 {
            get {
                return ResourceManager.GetString("StringGoodsDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails07 {
            get {
                return ResourceManager.GetString("StringGoodsDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tax Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails08 {
            get {
                return ResourceManager.GetString("StringGoodsDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails09 {
            get {
                return ResourceManager.GetString("StringGoodsDetails09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refund Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails10 {
            get {
                return ResourceManager.GetString("StringGoodsDetails10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Sales Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails11 {
            get {
                return ResourceManager.GetString("StringGoodsDetails11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Payable Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails12 {
            get {
                return ResourceManager.GetString("StringGoodsDetails12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Service Fee과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails13 {
            get {
                return ResourceManager.GetString("StringGoodsDetails13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Refund Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails14 {
            get {
                return ResourceManager.GetString("StringGoodsDetails14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Stores Total Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails15 {
            get {
                return ResourceManager.GetString("StringGoodsDetails15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Stores Total Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails16 {
            get {
                return ResourceManager.GetString("StringGoodsDetails16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---------------------------------------------------------------과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringLine {
            get {
                return ResourceManager.GetString("StringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運営会社과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringOperationName {
            get {
                return ResourceManager.GetString("StringOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REPRINT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRePublish {
            get {
                return ResourceManager.GetString("StringRePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETAILER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer {
            get {
                return ResourceManager.GetString("StringRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tax office concerned과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer01 {
            get {
                return ResourceManager.GetString("StringRetailer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place for Tax Payment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer02 {
            get {
                return ResourceManager.GetString("StringRetailer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seller&apos;s Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer03 {
            get {
                return ResourceManager.GetString("StringRetailer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seller&apos;s Place과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringRetailer04 {
            get {
                return ResourceManager.GetString("StringRetailer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refund No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipNo {
            get {
                return ResourceManager.GetString("StringSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Record of Purchase of Consumption
        ///Tax-Exempt for Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01 {
            get {
                return ResourceManager.GetString("StringSlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ① When departing Japan, or if becoming a resident of Japan, you are required to submit your &quot;Record of Purchase Card&quot; to either the Direct of Customs that has jurisdiction over your departure location or the head of the tax office that has jurisdiction over your place or residence or address.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ② You must not remove the &quot;Record of Purchase Card&quot; from your passport etc. until after you have departed Japan.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ③ If you are not in possession of item(s) purchase tax free, that are listed on the &quot;Record of Purchase Card&quot;, at the time of departure from Japan, an amount equivalent to the consumption tax amount(including local consumption tax) that was exempted at the time of purchase will be collected before your departure from Japan.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc03 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ④ In the case of ③ if you do not possess listed item(s) at the time of departure, if the Director of Customs has acknowledged that item(s) you purchased tax free will not be exported as a result of being lost in the disaster or due to other unavoidable circumstances, or alternatively, if you have submitted documents to the Director of curstoms that has jurisdiction over your departure location that verifies the item(s) has already been exported an amount equivalent till the consumption tax amount (including[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType01Desc04 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Covenant of Purchaser of Consumption
        ///Tax-Exempt of Ultimate Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02 {
            get {
                return ResourceManager.GetString("StringSlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I certify that the goods listed as &quot;consumable commodities&quot;on this card were purchased by me for export from Japan within 30days from the purchase date and will not be disposed of within Japan.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I certify that the goods listed as &quot;commodities except consumable&quot; on this card were purchased by me for ultimate export from Japan and will not be disposed of within Japan.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名　Signature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType02Signature {
            get {
                return ResourceManager.GetString("StringSlipType02Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Record of Purchase of Consumption
        ///Tax-Exempt for Export (For Copy)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType03 {
            get {
                return ResourceManager.GetString("StringSlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType04 {
            get {
                return ResourceManager.GetString("StringSlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Record of Purchase of Consumption
        ///Tax-Exempt for Export (Keep Sellers)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType05 {
            get {
                return ResourceManager.GetString("StringSlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합산발행전표과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06 {
            get {
                return ResourceManager.GetString("StringSlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합산발행순번과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringSlipType06No {
            get {
                return ResourceManager.GetString("StringSlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOURIST&apos;S DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails {
            get {
                return ResourceManager.GetString("StringTouristDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passport etc.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails01 {
            get {
                return ResourceManager.GetString("StringTouristDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails02 {
            get {
                return ResourceManager.GetString("StringTouristDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name in Full(in Block Letters)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails03 {
            get {
                return ResourceManager.GetString("StringTouristDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nationality과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails04 {
            get {
                return ResourceManager.GetString("StringTouristDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date of Birth과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails05 {
            get {
                return ResourceManager.GetString("StringTouristDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status of Residence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails06 {
            get {
                return ResourceManager.GetString("StringTouristDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place of Landing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails07 {
            get {
                return ResourceManager.GetString("StringTouristDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date of Landing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTouristDetails08 {
            get {
                return ResourceManager.GetString("StringTouristDetails08", resourceCulture);
            }
        }


        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails17
        {
            get
            {
                return ResourceManager.GetString("StringGoodsDetails17", resourceCulture);
            }
        }

        /// <summary>
        ///   购买日期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringGoodsDetails18
        {
            get
            {
                return ResourceManager.GetString("StringGoodsDetails18", resourceCulture);
            }
        }
    }
}
